version: '3.8'
services:
  catalogDb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
  catalog.api:
    image: catalog_api_img
    build:
      context: .
      dockerfile: \src\Services\Catalog.API\Dockerfile
  

volumes:
  catalogdb_volume:
  
  